spring:
  application:
    name: microservice-client
  datasource:
    url: jdbc:mysql://localhost:3306/client_db
    username: root
    password: marc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
server:
  port: 8082
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include=*: