spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: marc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
server:
  port: 8081